# Generated by Django 5.2 on 2025-04-30 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0004_empleado_habilidades'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='fecha_nac',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='pais',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='País'),
        ),
    ]
