# Generated by Django 5.2 on 2025-04-30 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0005_empleado_fecha_nac_empleado_pais'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='observaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fecha_nac',
            field=models.DateField(default='2000-01-01', verbose_name='Fecha de Nacimiento'),
            preserve_default=False,
        ),
    ]
